# Generated by Django 5.0.4 on 2024-04-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='geberated_content',
            new_name='generated_content',
        ),
    ]
